name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle Cloud
        uses: gradle/actions/setup-gradle@v3

      - name: Generation Wrapper & Compilation APK
        run: |
          gradle wrapper --gradle-version 8.2
          ./gradlew assembleDebug --stacktrace

      - name: Sauvegarde de l'APK en Artefact
        uses: actions/upload-artifact@v4
        with:
          name: etapka-debug
          path: app/build/outputs/apk/debug/app-debug.apk
